[env]
_.python.venv = ".venv"

UV_PUBLISH_USERNAME = "__token__"
UV_PUBLISH_PASSWORD = "<secret>"

# Local test env vars

REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_URL = "redis://{{env.REDIS_HOST}}:{{env.REDIS_PORT}}"
REDIS_POOL_SIZE = 10
REDIS_ASYNC_POOL_SIZE = 10

PYDANTIC_AI_GATEWAY_API_KEY = "<secret>"

[tasks.ci]
run = ["ruff format", "ruff check --fix", "ty check"]
